<?php

$publications = new Settings();

$publications->books = <<<EOF
en;Andrei Rimsa Álvares;Practical Dynamic Reconstruction of Control Flow Graphs;PhD Dissertation (Universidade Federal de Minas Gerais);2020;phd.pdf
en;Andrei Rimsa Álvares;Efficient Static Analysis to Find Tainted Variable Attacks;MsC Dissertation (Universidade Federal de Minas Gerais);2010;msc.pdf
EOF;

$publications->journals = <<<EOF
en;Andrei Rimsa, José Nelson Amaral, Fernando Magno Quintão Pereira;Instruction Visibility in SPEC CPU2017;Journal of Computer Languages;2021;jcl21.pdf
en;Andrei Rimsa, José Nelson Amaral, Fernando Magno Quintão Pereira;Practical Dynamic Reconstruction of Control Flow Graphs;Software, Practice and Experience;2021;spe21.pdf
en;Andrei Rimsa, Marcelo D'Amorim, Fernando Magno Quintão Pereira, Roberto S. Bigonha;Efficient Static Checker for Tainted Variable Attacks;Science of Computer Programming;2014;jscp14.pdf
EOF;

$publications->conferences = <<<EOF
pt;Andrei Rimsa, José Nelson Amaral, Fernando Magno Quintão Pereira;Construção Eficiente e Precisa de Grafos de Fluxo de Controle Dinâmicos;Simpósio Brasileiro de Linguagens de Programação (SBLP);2019;sblp19.pdf
en;Andrei Rimsa, Luis E. Zárate, Mark A. J. Song;SCGaz – A Synthetic Formal Context Generator with Density Control for Test and Evaluation of FCA Algorithms;IEEE International Conference on Systems, Man, and Cybernetics (SMC);2013;smc13.pdf
en;Andrei Rimsa, Marcelo d'Amorim, Fernando Magno Quintão Pereira;Tainted Flow Analysis on e-SSA-form Programs;International Conference on Compiler Construction (CC);2011;cc11.pdf
en;Andrei Rimsa, Marcelo d'Amorim, Fernando Magno Quintão Pereira;Efficient Static Checker for Tainted Variable Attacks;Simpósio Brasileiro de Linguagens de Programação (SBLP);2010;sblp10.pdf
en;Andrei Rimsa, Luis E. Zárate, Mark A. J. Song;Evaluation of Different BDD Libraries to Extract Concepts in FCA – Perspectives and Limitations;International Conference on Computational Science (ICCS);2009;iccs09.pdf
en;Andrei Rimsa, Luis E. Zárate, Mark A. J. Song;Handling Large Formal Context Using BDD – Perspectives and Limitations;International Conference on Formal Concept Analysis (ICFCA);2009;icfca09.pdf
EOF;

?>
