  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Andrei's Personal Homepage">
    <meta name="author" content="Andrei Rimsa Alvares">

    <title>Andrei Rimsa Alvares</title>

    <link rel="stylesheet" href="<?= $settings->basePage ?>/css/bootstrap.min.css">
    <link rel="stylesheet" href="<?= $settings->basePage ?>/css/jasny-bootstrap.min.css">
    <link rel="stylesheet" href="<?= $settings->basePage ?>/css/font-awesome.min.css">
    <link rel="stylesheet" href="<?= $settings->basePage ?>/css/social-icons.css">
    <link rel="stylesheet" href="<?= $settings->basePage ?>/css/rimsa.css">

    <!--[if lt IE 9]>
      <script src="<?= $settings->basePage ?>/js/html5shiv.js"></script>
      <script src="<?= $settings->basePage ?>/js/respond.min.js"></script>
    <![endif]-->
  </head>
