    <script src="<?= $settings->basePage ?>/js/jquery-1.10.2.min.js"></script>
    <script src="<?= $settings->basePage ?>/js/jquery.inputmask.bundle.min.js"></script>
    <script src="<?= $settings->basePage ?>/js/bootstrap.min.js"></script>
    <script src="<?= $settings->basePage ?>/js/jasny-bootstrap.min.js"></script>
    <script src="<?= $settings->basePage ?>/js/rimsa.js"></script>
    <script src="<?= $settings->basePage ?>/js/analytics.js"></script>
