<?php
	if (isset($settings->slideshow)) {
?>
        <div id="slideshow">
          <div class="ss-caption"></div>
          <img src="<?= $settings->basePage ?>/images/banner/brussels.jpg" alt="Parc du Cinquantenaire - Brussels, Belgium">
          <img src="<?= $settings->basePage ?>/images/banner/paris.jpg" alt="Pont Neuf - Paris, France">
          <img src="<?= $settings->basePage ?>/images/banner/versailles.jpg" alt="Château de Versailles - Versailles, France">
          <img src="<?= $settings->basePage ?>/images/banner/florianopolis.jpg" alt="Ponta das Campanhas - Florianópolis, SC/Brasil">
          <img src="<?= $settings->basePage ?>/images/banner/capitolio.jpg" alt="Cânions de Furnas - Capitólio, MG/Brasil">
          <img src="<?= $settings->basePage ?>/images/banner/lopo.jpg" alt="Serra do Lopo - Extrema, MG/Brasil">
          <img src="<?= $settings->basePage ?>/images/banner/bh.jpg" alt="Pico Belo Horizonte - Belo Horizonte, MG/Brasil">
          <img src="<?= $settings->basePage ?>/images/banner/juatinga.jpg" alt="Cachoeira do Saco Bravo - Juatinga, RJ/Brasil">
          <img src="<?= $settings->basePage ?>/images/banner/arraial.jpg" alt="Praia do Forno - Arraial do Cabo, RJ/Brasil">
          <img src="<?= $settings->basePage ?>/images/banner/vale-dos-frades.jpg" alt="Vale dos Frades - Nova Friburgo, RJ/Brasil">
          <img src="<?= $settings->basePage ?>/images/banner/serra-fina.jpg" alt="Serra Fina - Passa Quatro, MG/Brasil">
          <img src="<?= $settings->basePage ?>/images/banner/marins.jpg" alt="Marins - Piquete, MG/Brasil">
          <img src="<?= $settings->basePage ?>/images/banner/monte-verde.jpg" alt="Pedra Partida - Monte Verde, MG/Brasil">
          <img src="<?= $settings->basePage ?>/images/banner/sao-goncalo.jpg" alt="Poço do Veado - São Gonçalo do Rio Preto, MG/Brasil">
          <img src="<?= $settings->basePage ?>/images/banner/funil.jpg" alt="Cânion do Funil - Presidente Kubitschek, MG/Brasil">
          <img src="<?= $settings->basePage ?>/images/banner/itambe.jpg" alt="Pico do Itambé - Capivari, MG/Brasil">
          <img src="<?= $settings->basePage ?>/images/banner/fundao.jpg" alt="Cachoeira do Fundão - Serra da Canastra, MG/Brasil">
          <img src="<?= $settings->basePage ?>/images/banner/travessao.jpg" alt="Vale do Travessão - Serra da Cipó, MG/Brasil">
          <img src="<?= $settings->basePage ?>/images/banner/caparao.jpg" alt="Pico dos Cristais - Serra do Caparaó, MG/Brasil">
          <img src="<?= $settings->basePage ?>/images/banner/itatiaia.jpg" alt="Pico das Prateleiras - Itatiaia, RJ/Brasil">
          <img src="<?= $settings->basePage ?>/images/banner/lagoadourada.jpg" alt="Lagoa Dourada - São José da Serra, MG/Brasil">
          <img src="<?= $settings->basePage ?>/images/banner/peixetolo.jpg" alt="Cânion do Peixe Tolo - Conceição do Mato Dentro, MG/Brasil">
          <img src="<?= $settings->basePage ?>/images/banner/tresmarias.jpg" alt="Represa de Três Marias - Três Marias, MG/Brasil">
          <img src="<?= $settings->basePage ?>/images/banner/stockholm.jpg" alt="Helgeandsholmen Island - Stockholm, Sweden">
          <img src="<?= $settings->basePage ?>/images/banner/nuuksio.jpg" alt="Nuuksio National Park - Espoo, Finland">
          <img src="<?= $settings->basePage ?>/images/banner/oslo.jpg" alt="Royal Palace - Oslo, Norway">
          <img src="<?= $settings->basePage ?>/images/banner/vienna.jpg" alt="Hofburg - Vienna, Austria">
          <img src="<?= $settings->basePage ?>/images/banner/budapest.jpg" alt="Fisherman's Bastion - Budapest, Hungary">
          <img src="<?= $settings->basePage ?>/images/banner/kaunas.jpg" alt="Nemunas and Neris Confluence - Kaunas, Lithuania">
          <img src="<?= $settings->basePage ?>/images/banner/vilnius.jpg" alt="Cathedral Square - Vilnius, Lithuania">
          <img src="<?= $settings->basePage ?>/images/banner/bordeaux.jpg" alt="Saint-Émilion - Bordeaux, France">
          <img src="<?= $settings->basePage ?>/images/banner/berlin.jpg" alt="Berlin Wall - Berlin, Germany">
          <img src="<?= $settings->basePage ?>/images/banner/stmalo.jpg" alt="Grand Bé - Saint-Malo, France">
          <img src="<?= $settings->basePage ?>/images/banner/montstmichel.jpg" alt="Le Mont Saint-Michel - Mont Saint-Michel, France">
          <img src="<?= $settings->basePage ?>/images/banner/london.jpg" alt="Big Ben - London, United Kingdom">
          <img src="<?= $settings->basePage ?>/images/banner/prague.jpg" alt="Charles Bridge - Prague, Czech Republic">
          <img src="<?= $settings->basePage ?>/images/banner/veadeiros.jpg" alt="Cachoeiras do Salto 120 e 80 - Chapada dos Veadeiros, GO/Brasil">
          <img src="<?= $settings->basePage ?>/images/banner/setequedas.jpg" alt="Cachoeiras das 7 quedas - Lapinha da Serra, MG/Brasil">
          <img src="<?= $settings->basePage ?>/images/banner/bicame.jpg" alt="Cachoeiras do Bicame - Lapinha da Serra, MG/Brasil">
          <img src="<?= $settings->basePage ?>/images/banner/espinhaco.jpg" alt="Serra do Espinhaço - São João da Chapada, MG/Brasil">
          <img src="<?= $settings->basePage ?>/images/banner/tabuleiro.jpg" alt="Travessia Tabuleiro via Rota Norte - Tabuleiro, MG/Brasil">
          <img src="<?= $settings->basePage ?>/images/banner/adršpach.jpg" alt="Adršpach Lake - Adršpach, Czech Republic">
          <img src="<?= $settings->basePage ?>/images/banner/svatý-jan-pod-skalou.jpg" alt="Mountain View - Svatý Jan pod Skalou, Czech Republic">
          <img src="<?= $settings->basePage ?>/images/banner/sněžka.jpg" alt="Krkonoše Mountain - Sněžka, Czech Republic">
          <img src="<?= $settings->basePage ?>/images/banner/český-krumlov.jpg" alt="Castle - Český Krumlov, Czech Republic">
          <img src="<?= $settings->basePage ?>/images/banner/hallstatt.jpg" alt="Skywalk - Hallstatt, Austria">
          <img src="<?= $settings->basePage ?>/images/banner/stgilgen.jpg" alt="Wolfgangsee - St. Gilgen, Austria">
          <img src="<?= $settings->basePage ?>/images/banner/lakecomo.jpg" alt="Lago di Como - Como, Italia">
          <img src="<?= $settings->basePage ?>/images/banner/milano.jpg" alt="Arco de Triunfo - Milano, Italia">
          <img src="<?= $settings->basePage ?>/images/banner/venice.jpg" alt="Punta della Dogana - Venezia, Italia">
          <img src="<?= $settings->basePage ?>/images/banner/venice2.jpg" alt="Piazza San Marco - Venezia, Italia">
          <img src="<?= $settings->basePage ?>/images/banner/cinque-terre.jpg" alt="Vernazza - Cinque Terre, Italia">
          <img src="<?= $settings->basePage ?>/images/banner/pisa.jpg" alt="Torre di Pisa - Pisa, Italia">
          <img src="<?= $settings->basePage ?>/images/banner/florence.jpg" alt="Vigneto - Firenze, Italia"> 
          <img src="<?= $settings->basePage ?>/images/banner/rome.jpg" alt="Colosseum - Roma, Italia"> 
          <img src="<?= $settings->basePage ?>/images/banner/vatican.jpg" alt="Piazza San Pietro - Città del Vaticano, Italia">
          <img src="<?= $settings->basePage ?>/images/banner/aiuruoca.jpg" alt="Travessia Baependi x Aiuruoca - Aiuruoca, MG/Brasil">
          <img src="<?= $settings->basePage ?>/images/banner/delfinopolis.jpg" alt="Cachoeira do Zé Carlinho - Delfinópolis, MG/Brasil"> 
          <img src="<?= $settings->basePage ?>/images/banner/canastra.jpg" alt="Serra da Canastra - São Roque de Minas, MG/Brasil"> 
          <img src="<?= $settings->basePage ?>/images/banner/serradosalves.jpg" alt="Cânion Boca da Serra - Serra dos Alves, MG/Brasil">
          <img src="<?= $settings->basePage ?>/images/banner/riopreto.jpg" alt="Nascente do Rio Preto - São Gonçalo do Rio Preto, MG/Brasil">
          <img src="<?= $settings->basePage ?>/images/banner/cejar.jpg" alt="Laguna Cejar - San Pedro de Atacama, Chile">
          <img src="<?= $settings->basePage ?>/images/banner/tebinquinche.jpg" alt="Laguna Tebinquinche - San Pedro de Atacama, Chile">
          <img src="<?= $settings->basePage ?>/images/banner/altiplanicas.jpg" alt="Lagunas Altiplanicas - San Pedro de Atacama, Chile">
          <img src="<?= $settings->basePage ?>/images/banner/flamencos.jpg" alt="Los Flamencos National Reserve - San Pedro de Atacama, Chile">
          <img src="<?= $settings->basePage ?>/images/banner/valledelaluna.jpg" alt="Valle de la Luna - San Pedro de Atacama, Chile">
          <img src="<?= $settings->basePage ?>/images/banner/eltatio.jpg" alt="Geyser del Tatio - Antofagasta, Chile">
          <img src="<?= $settings->basePage ?>/images/banner/vadoputana.jpg" alt="Vado del Rio Putana - San Pedro de Atacama, Chile">
          <img src="<?= $settings->basePage ?>/images/banner/quitor.jpg" alt="Pukará de Quitor - San Pedro de Atacama, Chile">
          <img src="<?= $settings->basePage ?>/images/banner/lagunablanca.jpg" alt="Laguna Blanca - Sur Lípez, Bolivia">
          <img src="<?= $settings->basePage ?>/images/banner/lagunaverde.jpg" alt="Laguna Verde - Sur Lípez, Bolivia">
          <img src="<?= $settings->basePage ?>/images/banner/lagunacolorada.jpg" alt="Laguna Colorada - Sur Lípez, Bolivia">
          <img src="<?= $settings->basePage ?>/images/banner/lasrocas.jpg" alt="Valle de las Rocas - Sur Lípez, Bolivia">
          <img src="<?= $settings->basePage ?>/images/banner/uyuni.jpg" alt="Salar de Uyuni - Uyuni, Bolivia">
          <img src="<?= $settings->basePage ?>/images/banner/grey.jpg" alt="Glaciar Grey - Torres del Paine, Chile">
          <img src="<?= $settings->basePage ?>/images/banner/nordenskjöld.jpg" alt="Lago Nordenskjöld - Torres del Paine, Chile">
          <img src="<?= $settings->basePage ?>/images/banner/peritomoreno.jpg" alt="Glaciar Perito Moreno - El Calafate, Argentina">
          <img src="<?= $settings->basePage ?>/images/banner/losdedos.jpg" alt="Los Dedos - Punta del Este, Uruguay">
          <img src="<?= $settings->basePage ?>/images/banner/johnston.jpg" alt="Johnston Canyon - Banff, Canada">
          <img src="<?= $settings->basePage ?>/images/banner/bow.jpg" alt="Bow Lake, Banff, Canada">
          <img src="<?= $settings->basePage ?>/images/banner/sulphur.jpg" alt="Sulphur Mountain - Banff, Canada">
          <img src="<?= $settings->basePage ?>/images/banner/peyto.jpg" alt="Peyto Lake - Lake Louise, Canada">
          <img src="<?= $settings->basePage ?>/images/banner/louise.jpg" alt="Lake Louise - Lake Louise, Canada">
          <img src="<?= $settings->basePage ?>/images/banner/vancouver.jpg" alt="City View - Vancouver, Canada">
          <img src="<?= $settings->basePage ?>/images/banner/topkapi.jpg" alt="Topkapı Palace - Istanbul, Turkey">
          <img src="<?= $settings->basePage ?>/images/banner/suleymaniye.jpg" alt="Süleymaniye - Istanbul, Turkey">
          <img src="<?= $settings->basePage ?>/images/banner/kapadokya.jpg" alt="City View - Kapadokya, Turkey">
          <img src="<?= $settings->basePage ?>/images/banner/santorini.jpg" alt="Bell Tower - Santorini, Greece">
          <img src="<?= $settings->basePage ?>/images/banner/parthenon.jpg" alt="Parthenon - Athens, Greece">
          <img src="<?= $settings->basePage ?>/images/banner/oracle.jpg" alt="Oracle of Delphi - Delphi, Greece">
          <img src="<?= $settings->basePage ?>/images/banner/meteora.jpg" alt="City View - Meteora, Greece">
          <img src="<?= $settings->basePage ?>/images/banner/tabuleiro2.jpg" alt="Cachoeira do Tabuleiro - Conceição do Mato Dentro, MG/Brasil">
          <img src="<?= $settings->basePage ?>/images/banner/serramorena.jpg" alt="Cacheira da Serra Morena - Serra do Cipó, MG/Brasil">
          <img src="<?= $settings->basePage ?>/images/banner/morro.jpg" alt="Mirante Primeira Praia - Morro de São Paulo, BA/Brasil">
          <img src="<?= $settings->basePage ?>/images/banner/tourinhos.jpg" alt="Praia de Tourinhos - São Miguel do Gostoso, RN/Brasil">
          <img src="<?= $settings->basePage ?>/images/banner/amor.jpg" alt="Praia do Amor - Pipa, RN/Brasil">
          <img src="<?= $settings->basePage ?>/images/banner/genipabu.jpg" alt="Dunas - Genipabu, RN/Brasil">
          <img src="<?= $settings->basePage ?>/images/banner/cachoeiragrande.jpg" alt="Cachoeira Grande - Serra do Cipó, MG/Brasil">
          <img src="<?= $settings->basePage ?>/images/banner/serradapiedade.jpg" alt="Santuário Basílica Nossa Senhora da Piedade - Caeté, MG/Brasil">
          <img src="<?= $settings->basePage ?>/images/banner/cancun.jpg" alt="Playa Amada - Cancún, México">
          <img src="<?= $settings->basePage ?>/images/banner/canionfortaleza.jpg" alt="Cânion Fortaleza - Cambará do Sul, RS/Brasil">
          <img src="<?= $settings->basePage ?>/images/banner/canionitaimbezinho.jpg" alt="Cânion Itaimbezinho - Cambará do Sul, RS/Brasil">
          <img src="<?= $settings->basePage ?>/images/banner/riodoboi.jpg" alt="Trilha do Rio do Boi - Praia Grande, SC/Brasil">
          <img src="<?= $settings->basePage ?>/images/banner/sumitumba.jpg" alt="Cachoeira Sumitumba - Congonhas do Norte, MG/Brasil">
          <img src="<?= $settings->basePage ?>/images/banner/bode.jpg" alt="Cachoeira do Bode - Felício dos Santos, MG/Brasil">
          <img src="<?= $settings->basePage ?>/images/banner/sumidouro.jpg" alt="Cachoeira do Sumidouro - Felício dos Santos, MG/Brasil">
          <img src="<?= $settings->basePage ?>/images/banner/saomigueldosmilagres1.jpg" alt="Praia de São Miguel dos Milagres - São Miguel dos Milagres, AL/Brasil">
          <img src="<?= $settings->basePage ?>/images/banner/saomigueldosmilagres2.jpg" alt="Piscinas Naturais - São Miguel dos Milagres, AL/Brasil">
          <img src="<?= $settings->basePage ?>/images/banner/ruinasmosteirosaobento.jpg" alt="Ruínas do Mosteiro de São Bento - Maragogi, AL/Brasil">
        </div>
<?php
	}
?>
